config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  # resources :reviews
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :books do
    resources :reviews
  end
  resources :authors
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  has_many :reviews
  validates :name, presence: true, uniqueness: true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.haml
= form_with(model: author, local: true) do |form|
  - if author.errors.any?
    #error_explanation
      %h2
        = pluralize(author.errors.count, "error")
        prohibited this author from being saved:
      %ul
        - author.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name
  .actions
    = form.submit

app/views/authors/edit.html.haml
%h1 Editing Author
= render 'form', author: @author
= link_to 'Show', @author
|
= link_to 'Back', authors_path

app/views/authors/index.html.haml
%p#notice= notice
%h1 Authors
%table
  %thead
    %tr
      %th Name
      %th{:colspan => "3"}
  %tbody
    - @authors.each do |author|
      %tr
        %td= author.name
        %td= link_to 'Show', author
        %td= link_to 'Edit', edit_author_path(author)
        %td= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Author', new_author_path

app/views/authors/new.html.haml
%h1 New Author
= render 'form', author: @author
= link_to 'Back', authors_path

app/views/authors/show.html.haml
%p#notice= notice
%h2= @author.name
= link_to '編集', edit_author_path(@author)
.row
  - @author.books.each do |book|
    .col-2.p-4
      - if book.cover.present?
        = image_tag book.cover.url, class: "img-thumbnail"
      - else
        = image_tag "dummy.png", class: "img-thumbnail"
      %p= link_to book.name, book
      %p= book.author.name
      - if book.reviews.present?
        = ratystars(book.score, true)
        %br
        = "(" + book.reviews.count.to_s + "件のレビュー)"