config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  # resources :reviews
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :books do
    resources :reviews
  end
  resources :authors
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  has_many :reviews
  paginates_per 8
  mount_uploader :cover, CoverUploader
  validates :name, presence: true, uniqueness: {scope: :author}
  validates :author, presence: true
  validate :cover_size
  
  def score
    self.reviews.average(:score).floor(2)
  end
  
  private
  
    def cover_size
      if cover.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :get_authors, only: [:new, :edit, :update, :create]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /books
  # GET /books.json

  def  index 
    @q = Book.ransack(params[:q ])
    @books = @q.result(distinct: true).order(:name).page(params[:page])
    @authors = Author.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    # @book.cover = params[:cover] if params[:cover].present?
    # p @book.cover

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.' 
    else
      render :new
    end

    # respond_to do |format|
    #   if @book.save
    #     format.html { redirect_to @book, notice: 'Book was successfully created.' }
    #     format.json { render :show, status: :created, location: @book }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @book.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    # @book.cover = params[:cover] if params[:cover].present?
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:author_id, :name, :cover)
    end

    def get_authors
      @authors_array = Author.pluck(:id,:name).to_h.invert
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.1.haml
= form_with(model: book, local: true) do |form|
  - if book.errors.any?
    #error_explanation
      %h2
        = pluralize(book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - book.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :author_id
    = form.select :author_id, @authors_array
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :cover
    = form.file_field :cover, accept: 'image/jpeg,image/gif,image/png'
  %div
    = image_tag(@book.cover.url) if @book.cover.present?
  .actions
    = form.submit
:javascript
  $('#book_cover').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 1) {
      alert('Maximum file size is 1MB. Please choose a smaller file.');
    }
  });

app/views/books/_form.html.haml
= form_with(model: book, local: true) do |form|
  - if book.errors.any?
    #error_explanation
      %h2
        = pluralize(book.errors.count, "error")
        prohibited this book from being saved:
      %ul
        - book.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :author_id
    = form.select :author_id, @authors_array
  .field
    = form.label :name
    = form.text_field :name
  .field
    = form.label :cover
    = form.file_field :cover, accept: 'image/jpeg,image/gif,image/png'
  %div
    = image_tag(@book.cover.url) if @book.cover.present?
  .actions
    = form.submit
:javascript
  $('#book_cover').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 1) {
      alert('Maximum file size is 1MB. Please choose a smaller file.');
    }
  });

app/views/books/edit.html.haml
%h1 Editing Book
= render 'form', book: @book
= link_to 'Show', @book
|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h1 書籍一覧
.row.align-items-center.mb-1
  .col-4
    = search_form_for @q do |f|
      = f.search_field :name_cont
      = f.submit
  .col-8
    = paginate @books
  // .col-1
  //   = link_to new_book_path do
  //     %i.fas.fa-plus

.row.mb-1
  - @books.each do |book|
    .col-3.p-4
      - if book.cover.present?
        = image_tag book.cover.url, class: "img-thumbnail"
      - else
        = image_tag "dummy.png", class: "img-thumbnail"
      %p= link_to book.name, book
      %p= book.author.name
      - if book.reviews.present?
        = ratystars(book.score, true)
        %br
        = "(" + book.reviews.count.to_s + "件のレビュー)"
      %p
        = link_to '編集', edit_book_path(book), class: "btn btn-info btn-xs"
        = link_to '削除', book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs"

= link_to '本を登録する', new_book_path


// .modal{id: "myModal", :role => "dialog", :tabindex => "-1"}
//   .modal-dialog{:role => "document"}
//     .modal-content
//       .modal-header
//         %h5.modal-title Modal title
//         %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
//           %span{"aria-hidden" => "true"} ×
//       .modal-body
//         %p Modal body text goes here.
//       .modal-footer
//         %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
//         %button.btn.btn-primary{:type => "button"} Save changes

app/views/books/new.html.haml
%h1 New Book
= render 'form', book: @book
= link_to 'Back', books_path

app/views/books/show.html.haml
.row
  .col-4
    - if @book.cover.present?
      = image_tag(@book.cover.url)
    - else
      = image_tag("dummy.png")
  .col-6
    %h2
      = @book.name
    %h4 
      = link_to @book.author.name, @book.author
    %div
      - if @book.reviews.present?
        = ratystars(@book.reviews.average(:score).floor(2), true)
        .mt-5
          - @book.reviews.each do |review|
            .card.mb-2
              .card-header
                .row
                  .mr-auto.ml-3
                    %strong
                      = review.user.name + " さん"
                      = ratystars(review.score)
                  .ml-auto
                  - if user_signed_in? && review.user == current_user
                    %span.mx-1=link_to "編集", edit_book_review_path(@book,review)
                    %span.mx-1=link_to "削除", [@book,review], method: :delete, data: { confirm: 'Are you sure?' }
              .card-body
                = raw review.comment.gsub(/\r\n|\r|\n/, "<br />")
      - else
        まだレビューはありません。
      - if user_signed_in? && @book.reviews.where(user_id: current_user.id).present?
      - else
        = link_to 'レビューを書く', new_book_review_path(@book)

= link_to 'Edit', edit_book_path(@book)
|
= link_to 'Back', books_path

:javascript
  $('#star-rating').raty({
    path: '/assets/',
    click: 
      function(score, e) {
        $("#book_rating").val(score)
      }
  });