config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  # resources :reviews
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :books do
    resources :reviews
  end
  resources :authors
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :reviewer_check, only: [:edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @book = Book.find(params[:book_id])
    @review = @book.reviews.build
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @book = Book.find(params[:book_id])
    @review = @book.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      redirect_to @book, notice: 'レビューが投稿されました。'
    else
      render :new
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if @review.update(review_params)
      redirect_to @book, notice: 'レビューが更新されました。'
    else
      render :edit
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    redirect_to @book, notice: 'Review was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @book = Book.find(params[:book_id])
      @review = Review.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:book_id, :user_id, :score, :comment)
    end

    def reviewer_check
      redirect_to @book, notice: "you are note reviewer." if @review.user != current_user
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= form_with(model: [@book, @review], local: true) do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :score
    = f.hidden_field :score, id: :book_rating
    #star-rating

  .field
    = f.label :comment
    = f.text_area :comment, class: "form-control", rows: "5" 
  .actions
    = f.submit '投稿する'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Back', @book

app/views/reviews/index.html.haml
%h1
  = @book.name

%table
  %thead
    %tr
      %th User
      %th Score
      %th Comment
      %th
      %th
      %th

  %tbody
    - @reviews.each do |review|
      %tr
        %td= review.user.email
        %td= review.score
        %td= review.comment
        %td= link_to 'Show', book_review_path(@book, review)
        %td= link_to 'Edit', edit_book_review_path(@book, review)
        %td= link_to 'Destroy', book_review_path(@book, review), method: :delete, data: { confirm: 'Are you sure?' }

%br

// = link_to 'New Review', new_book_review_path

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', @book

app/views/reviews/show.html.haml
%p
  %b Book:
  = @review.book.name
%p
  %b User:
  = @review.user.email
%p
  %b Score:
  = @review.score
%p
  %b Comment:
  = @review.comment

= link_to 'Edit', edit_book_review_path(@book, @review)
\|
= link_to 'Back', @book