config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  # resources :reviews
  devise_for :users
  resources :users, :only => [:index, :show]
  resources :books do
    resources :reviews
  end
  resources :authors
  root 'books#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BookReviewer
    = csrf_meta_tags
    = csp_meta_tag
    // = stylesheet_link_tag    'sticky-footer-navbar', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.5.0/css/all.css", :integrity => "sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU", :rel => "stylesheet"}/
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css", :integrity => "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO", :rel => "stylesheet"}/
    %script{:crossorigin => "anonymous", :integrity => "sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo", :src => "https://code.jquery.com/jquery-3.3.1.slim.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49", :src => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"}
    %script{:crossorigin => "anonymous", :integrity => "sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=", :src => "https://code.jquery.com/jquery-3.3.1.min.js"}

    %script{:crossorigin => "anonymous", :integrity => "sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy", :src => "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %header
      / Fixed navbar
      %nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
        = link_to 'Book-Reviewer', root_path, class: "navbar-brand"
        %button.navbar-toggler{"aria-controls" => "navbarCollapse", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarCollapse.collapse.navbar-collapse
          %ul.navbar-nav.mr-auto
            %li.nav-item.active
              = link_to 'Home', root_path, class: "nav-link"
          %ul.navbar-nav
            - if user_signed_in?
              %li.nav-item.active
                = link_to current_user.email, user_path(current_user), class: "nav-link"
              %li.nav-item.active
                = link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"btn btn-outline-primary btn-sm"
            - else
              %li.nav-item.active
                = link_to 'ログイン', new_user_session_path, method: :get, class:"btn btn-outline-success btn-sm"
    .container
      %p#notice= notice
      = yield

app/views/layouts/sample.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    %link{:href => "../../favicon.ico", :rel => "icon"}/
    %title Starter Template for Bootstrap
    %link{:href => "https://getbootstrap.com/docs/4.0/examples/starter-template/", :rel => "canonical"}/
    / Bootstrap core CSS
    %link{:href => "../../dist/css/bootstrap.min.css", :rel => "stylesheet"}/
    / Custom styles for this template
    %link{:href => "starter-template.css", :rel => "stylesheet"}/
  %body
    %nav.navbar.navbar-toggleable-md.navbar-inverse.bg-inverse.fixed-top
      %button.navbar-toggler.navbar-toggler-right{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      %a.navbar-brand{:href => "#"} Navbar
      #navbarsExampleDefault.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            %a.nav-link{:href => "#"}
              Home
              %span.sr-only (current)
          %li.nav-item
            %a.nav-link{:href => "#"} Link
          %li.nav-item
            %a.nav-link.disabled{:href => "#"} Disabled
          %li.nav-item.dropdown
            %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "http://example.com"} Dropdown
            .dropdown-menu{"aria-labelledby" => "dropdown01"}
              %a.dropdown-item{:href => "#"} Action
              %a.dropdown-item{:href => "#"} Another action
              %a.dropdown-item{:href => "#"} Something else here
        %form.form-inline.my-2.my-lg-0
          %input.form-control.mr-sm-2{:placeholder => "Search", :type => "text"}/
          %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Search
    .container
      .starter-template
        %h1 Bootstrap starter template
        %p.lead
          Use this document as a way to quickly start any new project.
          %br/
          All you get is this text and a mostly barebones HTML document.
    / /.container
    /
      Bootstrap core JavaScript
      \==================================================
    / Placed at the end of the document so the pages load faster
    %script{:crossorigin => "anonymous", :integrity => "sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n", :src => "https://code.jquery.com/jquery-3.1.1.slim.min.js"}
    :javascript
      window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
    %script{:crossorigin => "anonymous", :integrity => "sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb", :src => "https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"}
    %script{:src => "../../dist/js/bootstrap.min.js"}
    / IE10 viewport hack for Surface/desktop Windows 8 bug
    %script{:src => "../../assets/js/ie10-viewport-bug-workaround.js"}